#!/usr/bin/env bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ BITE-OS HEALTH CHECK & SELF-REPAIR
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Runs at every login (systemd user service). Cheap + idempotent: when the
# config is healthy it only reads a few files. When the ilyamiro rice's
# autogenerated keybinds look wiped (the classic empty-settings.json failure),
# it repairs — first by recompiling, then by restoring from the vault snapshot.
#
# This is the safety net for the ISO: a fresh install can't boot to a dead
# desktop and stay there.
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
set -uo pipefail

RICES="$HOME/.local/share/bite-os/rices"
HYPR="$HOME/.config/hypr"
STATE_DIR="$HOME/.local/state/bite-os"
LOG="$STATE_DIR/healthcheck.log"
mkdir -p "$STATE_DIR"

log() { printf '[%s] %s\n' "$(date '+%F %T')" "$*" >> "$LOG"; }
: > "$LOG"
log "=== BITE-OS health check ==="

ACTIVE="$(cat "$RICES/.active" 2>/dev/null || echo '')"
log "active rice: ${ACTIVE:-unknown}"

# ── 1. Validate the ilyamiro vault snapshot (the autogen-driven rice) ────────
ILYA="$RICES/ilyamiro/.config/hypr"
vault_ok=1
for t in keybinds env autostart settings monitors; do
    if [ ! -s "$ILYA/templates/$t.conf.template" ]; then
        log "VAULT: missing/empty template $t.conf.template"; vault_ok=0
    fi
done
if [ -f "$ILYA/settings.json" ]; then
    kb_count="$(jq '.keybinds | length' "$ILYA/settings.json" 2>/dev/null || echo 0)"
    log "VAULT: settings.json keybinds = ${kb_count:-0}"
    [ "${kb_count:-0}" -lt 1 ] && vault_ok=0
else
    log "VAULT: settings.json MISSING"; vault_ok=0
fi
[ "$vault_ok" -eq 1 ] && log "VAULT: ilyamiro snapshot OK" || log "VAULT: ilyamiro snapshot DEGRADED"

# ── 2. If ilyamiro is the live rice, validate + repair the running config ────
if [ "$ACTIVE" = "ilyamiro" ]; then
    KB="$HYPR/config/keybindings.conf"
    binds="$(grep -c '^bind' "$KB" 2>/dev/null || echo 0)"
    log "LIVE: keybindings.conf has $binds bind lines"

    if [ "${binds:-0}" -lt 5 ]; then
        log "REPAIR: keybinds look wiped — recompiling from settings.json"
        bash "$HYPR/scripts/settings_watcher.sh" --compile >> "$LOG" 2>&1
        binds="$(grep -c '^bind' "$KB" 2>/dev/null || echo 0)"
        log "REPAIR: after recompile = $binds bind lines"

        if [ "${binds:-0}" -lt 5 ] && [ "$vault_ok" -eq 1 ]; then
            log "REPAIR: still broken — restoring ilyamiro from vault snapshot"
            "$HOME/.config/glitch/bin/rice" load ilyamiro >> "$LOG" 2>&1
            hyprctl reload >> "$LOG" 2>&1
            binds="$(grep -c '^bind' "$KB" 2>/dev/null || echo 0)"
            log "REPAIR: after vault restore = $binds bind lines"
        fi

        if [ "${binds:-0}" -ge 5 ]; then
            log "REPAIR: success"
            notify-send -a "BITE-OS" "Config repaired" \
                "Keybinds were wiped and have been restored automatically." 2>/dev/null || true
        else
            log "REPAIR: FAILED — manual recovery needed (Super+Ctrl+D to swap, or 'rice rollback')"
            notify-send -a "BITE-OS" -u critical "Config repair failed" \
                "Press Super+Ctrl+D to swap dots, or run 'rice rollback' from a TTY." 2>/dev/null || true
        fi
    else
        log "LIVE: config healthy, no action"
    fi
else
    log "LIVE: active rice is not ilyamiro — skipping live repair"
fi

log "=== health check done ==="
exit 0
